### ISSUE TITLE
API to validate xml files

### ISSUE THREAD

**Issue by estedeahora** [JATS4R/jats-validator-ui#41]
Is there any way to validate documents automatically from a request / API? I would need a "machine interface" (API), which allows this request to be made automatically as part of an editorial flow. I think it would be a very good addition (if it doesn't currently exist).

**Comment by hubgit** [comment]
You can post JATS XML files to [the endpoint that the JATS4R validator uses](https://jats-validator.hubmed.org/) for validation.

**Comment by estedeahora** [comment]
> You can post JATS XML files to [the endpoint that the JATS4R validator uses](https://jats-validator.hubmed.org/) for validation.

Thank you very much, I was not aware of this possibility!
